[package]
name = "hades252"
version = "0.10.1"
authors = [
  "kev <kevtheappdev@gmail.com>", "zer0 <matteo@dusk.network>",
  "Victor Lopes <victor@dusk.network>", "kr0 <c.perezbaro@gmail.com>"
]
edition = "2018"
build="build/build.rs"

[dependencies]
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
dusk-bls12_381 = {git="https://github.com/dusk-network/bls12_381", branch="vlopes11/g1affine-raw-bytes", default-features=false}
dusk-plonk = {git="https://github.com/dusk-network/plonk", branch="vlopes11/332-proverkey-from-unchecked", optional=true}

[dev-dependencies]
rand = "0.8"
criterion = "0.3"
anyhow = "1.0.0"

[build-dependencies]
sha2 = "0.8"
dusk-bls12_381 = {git="https://github.com/dusk-network/bls12_381", branch="vlopes11/g1affine-raw-bytes", default-features=false}

[profile.release]
panic = 'abort'
lto = true
incremental = false
codegen-units = 1

[features]
default = ["std"]
nightly_docs = []
std = ["dusk-plonk", "dusk-bls12_381/default"]
