[package]
name = "hades252"
version = "0.1.0"
authors = ["kev <kevtheappdev@gmail.com>"]
edition = "2018"

[dependencies.curve25519-dalek]
version = "1"
features = ["nightly"]


[dependencies]
"hex" = "0.3.1"
"sha2" = "0.8"