[package]
name = "hades252"
version = "0.8.0"
authors = [
  "kev <kevtheappdev@gmail.com>", "zer0 <matteo@dusk.network>",
  "Victor Lopes <victor@dusk.network>", "kr0 <c.perezbaro@gmail.com>"
]
edition = "2018"
build="build/build.rs"

[dependencies]
lazy_static = "1.3.0"
dusk-plonk = {version = "0.2.11", features = ["trace-print"]}

[features]
nightly_docs = []

[dependencies.tracing]
version = "0.1"
optional = true

[dev-dependencies]
rand = "0.7"
criterion = "0.3"
anyhow = "1.0.0"

[build-dependencies]
sha2 = "0.8"
dusk-plonk = {version = "0.2.11", features = ["trace-print"]}

[profile.release]
panic = 'abort'
lto = true
incremental = false
codegen-units = 1
target-cpu = "native"
