[package]
name = "hades252"
version = "0.10.0"
authors = [
  "kev <kevtheappdev@gmail.com>", "zer0 <matteo@dusk.network>",
  "Victor Lopes <victor@dusk.network>", "kr0 <c.perezbaro@gmail.com>"
]
edition = "2018"
build="build/build.rs"

[dependencies]
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }

[dependencies.dusk-plonk]
git = "https://github.com/dusk-network/plonk"
branch = "vlopes11/no-std-scalar"
optional = true

[dependencies.dusk-bls12_381]
git = "https://github.com/dusk-network/bls12_381"
branch = "vlope11/scalar-no-std"
default-features = false

[dev-dependencies]
rand = "0.7"
criterion = "0.3"
anyhow = "1.0.0"

[build-dependencies]
sha2 = "0.8"

[build-dependencies.dusk-bls12_381]
git = "https://github.com/dusk-network/bls12_381"
branch = "vlope11/scalar-no-std"
default-features = false

[profile.release]
panic = 'abort'
lto = true
incremental = false
codegen-units = 1

[features]
default = ["std"]
nightly_docs = []
std = ["dusk-plonk"]
